"""Small, deterministic compliance post-processing for final responses.

This module is deliberately a keyword-and-disclaimer guardrail.  It does not
claim to determine regulatory compliance or rewrite substantive advice.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any


_POLICY_PATH = Path(__file__).resolve().parents[1] / "data" / "config" / "compliance.json"
_DEFAULT_KEYWORDS = ("guarantee", "guaranteed", "must pay")
_DEFAULT_DISCLAIMER = (
    "This response is generated by AI for internal reference only and does not "
    "constitute a commitment, recommendation, or official explanation."
)


def _default_policy() -> tuple[tuple[str, ...], str]:
    """Return the narrow policy used only when the local policy is unusable."""
    return _DEFAULT_KEYWORDS, _DEFAULT_DISCLAIMER


def _load_policy() -> tuple[tuple[str, ...], str]:
    """Load a valid local policy, or use the documented deterministic fallback."""
    try:
        raw_policy: Any = json.loads(_POLICY_PATH.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return _default_policy()

    if not isinstance(raw_policy, dict):
        return _default_policy()

    keywords = raw_policy.get("keywords")
    disclaimer = raw_policy.get("disclaimer")
    if (
        not isinstance(keywords, list)
        or not keywords
        or not isinstance(disclaimer, str)
        or not disclaimer.strip()
    ):
        return _default_policy()

    ordered_keywords: list[str] = []
    seen_keywords: set[str] = set()
    for keyword in keywords:
        if not isinstance(keyword, str) or not keyword.strip():
            return _default_policy()
        canonical_keyword = keyword.strip()
        casefolded_keyword = canonical_keyword.casefold()
        if casefolded_keyword not in seen_keywords:
            ordered_keywords.append(canonical_keyword)
            seen_keywords.add(casefolded_keyword)

    return tuple(ordered_keywords), disclaimer


def apply_compliance(text: str) -> tuple[str, bool, list[str]]:
    """Append a configured disclaimer when configured keywords match ``text``.

    Matching is case-insensitive and returned keywords keep the policy's declared
    order.  The original answer is never removed or rewritten.
    """
    keywords, disclaimer = _load_policy()
    casefolded_text = text.casefold()
    matched_keywords = [
        keyword for keyword in keywords if keyword.casefold() in casefolded_text
    ]

    if not matched_keywords:
        return text, False, []

    if disclaimer in text:
        return text, True, matched_keywords

    separator = "\n\n" if text else ""
    return f"{text}{separator}{disclaimer}", True, matched_keywords
